baseURL = 'https://blog.88886688.xyz/'
languageCode = 'en-us'
title = "Lester's Blog"
theme = 'PaperMod'
[menu]
[[menu.main]]
  name = 'Home'
  identifier = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  name = 'Tags/分类'
  identifier = 'Tags/分类'
  url = '/tags'
  weight = 20
[[menu.main]]
  name = 'Pi3B/树莓派3B'
  identifier = 'RaspberryPi3B'
  url = '/raspberrypi3b-post'
  weight = 30
[[menu.main]]
  name = 'About/关于'
  identifier = 'About/关于'
  url = '/about'
  weight = 40
[params]
  ShowPostNavLinks = true
  showtoc = true
  ShowReadingTime = true
  ShowWordCount = true
  ShowCodeCopyButtons = true
  RaspberrypiImg = 'https://i.imgur.com/I1ACwsc.jpg'
  AboutImg = 'https://i.imgur.com/rG3ZbYv.jpg'